name: Build & Deploy React App
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'checkout branch'
        uses: actions/checkout@v1
        with:
          ref: main
      - name: 'Npm Install'
        run: npm install
      - name: 'Npm Build'
        run: npm run build
      - name: 'Create env file'
        run: |
          touch .env
          echo REACT_APP_TREE_API_URL=${{ secrets.REACT_APP_TREE_API_URL }} >> .env
      - name: 'Deploy to S3'
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY_ID }}
          SOURCE_DIR: 'build'
